[workspace]
members = [
    "circuits/transfer",
    "circuits/license",

    # Test contracts
    "contracts/alice",
    "contracts/bob",
    "contracts/charlie",
    "contracts/host_fn",

    # Genesis contracts
    "contracts/stake",
    "contracts/transfer",
    "contracts/license",

    "execution-core",

    "rusk-prover",

    "rusk-recovery",
    "rusk-profile",
    "rusk-abi",
    "rusk",

    "node-data",
    "consensus",
    "node",
]
resolver = "2"

[profile.dev.build-override]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16

[profile.release.build-override]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16

[profile.release.package.stake-contract]
overflow-checks = true

[profile.release.package.transfer-contract]
overflow-checks = true
