[package]
name = "alice"
version = "0.3.0"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
phoenix-core = { version = "0.18", default-features = false, features = ["rkyv-impl", "alloc"] }
rusk-abi = { version = "0.9.0-piecrust.0.6", path = "../../rusk-abi" }
dusk-pki = { version = "0.11", default-features = false, features = ["rkyv-impl"] }
