[package]
name = "stake-contract"
version = "0.8.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
execution-core = { version = "0.1.0", path = "../../execution-core" }
dusk-bytes = "0.1"
dusk-plonk = { version = "0.19", default-features = false, features = ["rkyv-impl", "alloc"] }
rkyv = { version = "0.7", default-features = false, features = ["size_32"] }

[target.'cfg(target_family = "wasm")'.dependencies]
rusk-abi = { version = "0.13.0-rc", path = "../../rusk-abi" }

[dev-dependencies]
rusk-profile = { version = "0.6", path = "../../rusk-profile" }
rusk-abi = { version = "0.13.0-rc", path = "../../rusk-abi", default-features = false, features = ["host"] }
transfer-circuits = { version = "0.5", path = "../../circuits/transfer" }
rkyv = { version = "0.7", default-features = false, features = ["size_32"] }
hex = "0.4"
rand = "0.8"
poseidon-merkle = { version = "0.5", features = ["rkyv-impl"] }
ff = { version = "0.13", default-features = false }
criterion = "0.5"

[[bench]]
name = "get_provisioners"
harness = false
