[package]
name = "stake-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
canonical = "0.6"
canonical_derive = "0.6"
dusk-abi = "0.10"
dusk-bytes = "0.1"
dusk-hamt = { version = "0.5", default-features = false }
dusk-pki = { version = "0.9.0-rc", default-features = false }
dusk-schnorr = { version = "0.9.0-rc", default-features = false, features = ["canon"] }
dusk-bls12_381 = { version = "0.8", default-features = false, features = ["canon"] }
phoenix-core = { version = "0.15.0-rc", default-features = false, features = ["canon"] }

transfer-contract = { path = "../transfer", default-features = false, features = ["no-bridge"] }
rusk-abi = { path = "../../rusk-abi", features = ["module"] }

[features]
default = ["transfer-contract/circuits"]
