[package]
name = "bob"
version = "0.3.0"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rusk-abi = { version = "0.8.0-alpha", path = "../../rusk-abi", features = ["debug"] }

[dev-dependencies]
rusk-abi = { version = "0.8.0-alpha", path = "../../rusk-abi", default-features = false, features = ["host"] }
