[package]
name = "bid-circuits"
version = "0.1.0"
authors = ["Jules de Smit <jules@dusk.network>"]
edition = "2018"


[dependencies]
anyhow = "1"
dusk-plonk = "0.5"
plonk_gadgets = {git = "https://github.com/dusk-network/plonk_gadgets", tag = "v0.5.0"}
dusk-blindbid = { git = "https://github.com/dusk-network/dusk-blindbid", tag = "v0.5.1"}
rand = "0.7"
