[package]
name = "transfer-contract"
version = "0.10.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
execution-core = { version = "0.1.0", path = "../../execution-core" }
dusk-bytes = "0.1"
rkyv = { version = "0.7", default-features = false, features = ["size_32"] }
ringbuffer = "0.15"


[target.'cfg(target_family = "wasm")'.dependencies]
rusk-abi = { version = "0.13.0-rc", path = "../../rusk-abi" }

[dev-dependencies]
rusk-profile = { version = "0.6", path = "../../rusk-profile" }
once_cell = { version = "1.9" }
rusk-abi = { version = "0.13.0-rc", path = "../../rusk-abi", default-features = false, features = ["host"] }
rusk-prover = { version = "0.5", path = "../../rusk-prover/" }
rkyv = { version = "0.7", default-features = false, features = ["size_32"] }
bytecheck = { version = "0.6", default-features = false }
hex = "0.4"
rand = "0.8"
ff = { version = "0.13", default-features = false }

[build-dependencies]
rusk-profile = { version = "0.6", path = "../../rusk-profile"}
