[package]
name = "transfer-contract"
version = "0.4.0"
authors = ["Victor Lopez <victor@dusk.network>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
canonical = "0.6"
canonical_derive = "0.6"
rusk-abi = { path = "../../rusk-abi" }
dusk-abi = "0.9.0-rc"
dusk-bytes = "0.1"
dusk-bls12_381 = { version = "0.8", default-features = false, features = ["canon"] }
dusk-jubjub = { version = "0.10", default-features = false, features = ["canon"] }
dusk-poseidon = { version = "0.21.0-rc", default-features = false, features = ["canon"] }
dusk-pki = { version = "0.7.0-rc", default-features = false }
phoenix-core = { version = "0.11.0-rc", default-features = false, features = ["canon"] }
dusk-hamt = { version = "0.3", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
lazy_static = "1.4"
rand = "0.8"
rusk = { path = "../../rusk" }
transfer-circuits = { path = "../../circuits/transfer", features = ["builder"] }
rusk-profile = { path = "../../rusk-profile" }
dusk-plonk = "0.8"
