[package]
name = "license"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dusk-bls12_381 = { version = "0.11", default-features = false, features = ["rkyv-impl"] }
dusk-bytes = "0.1"
dusk-jubjub = { version = "0.12", default-features = false, features = ["rkyv-impl"] }
dusk-pki = { version = "0.12", default-features = false, features = ["rkyv-impl"] }
dusk-poseidon = { version = "0.30", default-features = false, features = ["alloc"] }
poseidon-merkle = { version = "0.2.1-rc.0", features = ["rkyv-impl"] }
dusk-plonk = { version = "0.14", default-features = false, features = ["rkyv-impl", "alloc"] }
rkyv = { version = "0.7", default-features = false, features = ["size_32"] }
bytecheck = { version = "0.6", default-features = false }
contract-helpers = { version = "0.1", path = "../../contract-helpers" }
dusk-schnorr = { version = "0.13", default-features = false, features = ["rkyv-impl"] }

[target.'cfg(target_family = "wasm")'.dependencies]
rusk-abi = { version = "0.10.0-piecrust.0.6", path = "../../rusk-abi" }

[dev-dependencies]
rusk-abi = { version = "0.10.0-piecrust.0.6", path = "../../rusk-abi", default-features = false, features = ["host"] }
license-circuits = { version = "0.1", path = "../../circuits/license" }
rkyv = { version = "0.7", default-features = false }
hex = "0.4"
rand = "0.8"
zk-citadel = { version = "0.4", git = "https://github.com/dusk-network/citadel", tag = "0.4.1-rc.0" }
