[package]
name = "license-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
execution-core = { workspace = true, features = ["zk"] }
dusk-bytes = { workspace = true }
rkyv = { workspace = true, features = ["size_32"] }
bytecheck = { workspace = true }

[target.'cfg(target_family = "wasm")'.dependencies]
rusk-abi = { workspace = true, features = ["abi", "dlmalloc"] }

[dev-dependencies]
rusk-abi = { workspace = true, features = ["host"] }
rusk-profile = { workspace = true }
license-circuits = { workspace = true }
rand = { workspace = true }
zk-citadel = { workspace = true }
ff = { workspace = true }
dusk-poseidon = { workspace = true }

[build-dependencies]
rusk-profile = { workspace = true }
