[package]
name = "license-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
execution-core = { version = "0.1.0", path = "../../execution-core", features = ["zk"] }
dusk-bytes = "0.1"
dusk-poseidon = "0.39"
poseidon-merkle = { version = "0.6", features = ["rkyv-impl", "zk", "size_32"] }
rkyv = { version = "0.7", default-features = false, features = ["size_32"] }
bytecheck = { version = "0.6", default-features = false }

[target.'cfg(target_family = "wasm")'.dependencies]
rusk-abi = { version = "0.13.0-rc", path = "../../rusk-abi" }

[dev-dependencies]
rusk-abi = { version = "0.13.0-rc", path = "../../rusk-abi", default-features = false, features = ["host"] }
rusk-profile = { version = "0.6", path = "../../rusk-profile"}
license-circuits = { version = "0.1", path = "../../circuits/license" }
rkyv = { version = "0.7", default-features = false, features = ["size_32"] }
hex = "0.4"
rand = "0.8"
zk-citadel = "0.12.0-rc"
ff = { version = "0.13", default-features = false }

[build-dependencies]
rusk-profile = { version = "0.6", path = "../../rusk-profile"}
