[package]
name = "rusk-profile"
version = "0.3.0"
authors = ["zer0 <matteo@dusk.network>"]
edition = "2018"
autobins = false

[dependencies]
dirs = "3.0"
tracing = "0.1"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
