[package]
name = "rusk-profile"
version = "0.6.0"
edition = "2021"
autobins = false

[dependencies]
dirs = "4.0"
tracing = "0.1"
hex = "0.4"
sha2 = "0.10"
blake3 = "1.3"
toml = "0.7"
serde = { version = "1", features = ["derive"] }
console = "0.12"
version_check = "0.9"
