[package]
name = "governance-contract"
version = "0.12.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dusk-bls12_381 = { version = "0.11", default-features = false, features = ["rkyv-impl"] }
dusk-bls12_381-sign = { version = "0.4", default-features = false, features = ["rkyv-impl"] }
dusk-bytes = "0.1"
dusk-pki = { version = "0.11", default-features = false, features = ["rkyv-impl"] }
rusk-abi = { version = "0.8.0-alpha", path = "../../rusk-abi" }
rkyv = { version = "0.7", default-features = false }

[dev-dependencies]
rusk-abi = { version = "0.8.0-alpha", path = "../../rusk-abi", default-features = false, features = ["host"] }
rand = "0.8"
