[package]
name = "node"
version = "0.1.0"
edition = "2021"
autobins = false
description = "An implementation of dusk-blockchain node in pure Rust"
categories = ["cryptography", "cryptography::cryptocurrencies"]
keywords = ["dusk", "cryptocurrency", "blockchain", "node"]
license = "MPL-2.0"

[[bin]]
name = "rusk-node"
path = "src/bin/main.rs"


[dependencies]
tracing = "0.1"
hex = "0.4"
dusk-consensus = "0.1"
kadcast = "0.5.0-rc"
sha3 = { version = "0.10" }
anyhow = "1.0"
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3.16"
async-channel = "1.7"

rocksdb_lib = { package = "rocksdb", version = "0.19.0", default-features = false }
dusk-wallet-core = "0.14.0-rc.0"
dusk-bytes = "^0.1"
node-common = { path = "../node-common", version = "0.1" }

[dev-dependencies]
fake = { version = "2.5", features=['derive']}
rand = "0.8"
rand_core = "0.6"

