# Temporary fix to avoid Makefile just for wasm, until we figure out how to
# run `cargo test` for the host machine with the default target `wasm32`
#
# See: <https://github.com/rust-lang/cargo/issues/6784>
[alias]
wasm = "build --release --target wasm32-unknown-unknown -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort"
wasm-debug = "build --target wasm32-unknown-unknown -Z build-std=std,panic_abort"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = false
debug = false
strip = "symbols"
incremental = false
rpath = false
