[package]
name = "rusk-recovery"
version = "0.1.0"
edition = "2021"
autobins = false
description = "Tool to restore Rusk to factory settings"

[lib]
name = "rusk_recovery_tools"
path = "src/lib.rs"

[[bin]]
name = "rusk-recovery-keys"
path = "src/bin/keys.rs"
required-features = ["keys"]

[[bin]]
name = "rusk-recovery-state"
path = "src/bin/state.rs"
required-features = ["state"]

[build-dependencies]
rustc_tools_util = "0.2"

[dependencies]
hex = "0.4"
rustc_tools_util = "0.2"
dusk-plonk = { version = "0.9", features = ["canon", "std"] }
dusk-pki = "0.9.0-rc"
phoenix-core = "0.15.0-rc"
rand = "0.8"
transfer-circuits = { path = "../circuits/transfer", features=["builder"] }
transfer-contract = { path = "../contracts/transfer", default-features = false }
stake-contract = { path = "../contracts/stake", default-features = false }
microkelvin = { version = "0.10", features = ["persistence"] }
rusk-vm = { version = "0.7.0-rc", features = ["persistence"] }
rusk-profile = { path = "../rusk-profile" }
rusk-abi = { path = "../rusk-abi" }
lazy_static = "1.4"
canonical = "0.6"
canonical_derive = "0.6"
dusk-bls12_381 = "0.8"
clap = { version = "3.0", features = ["cargo", "env", "derive"] }
thiserror = "1.0"
console = "0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.2.0", features = ["fmt"] }

[features]
state = []
keys = []
