[package]
name = "rusk-prover"
version = "0.3.0"
edition = "2021"
autobins = false

[dependencies]
dusk-bytes = { version = "0.1" }
dusk-plonk = { version = "0.19", default-features = false }
poseidon-merkle = { version = "0.5", features = ["rkyv-impl"] }
rand_core = "0.6"

rkyv = { version = "0.7", default-features = false, features = ["size_32"] }
bytecheck = { version = "0.6", default-features = false }

rusk-abi = { version = "0.13.0-rc", path = "../rusk-abi", default-features = false }
execution-core = { version = "0.1.0", path = "../execution-core" }

## feature local_prover
once_cell = { version = "1.9", optional = true }
rand = { version = "0.8", optional = true }
rusk-profile = { version = "0.6", path = "../rusk-profile", optional = true }
transfer-circuits = { version = "0.5", path = "../circuits/transfer", optional = true }

[dev-dependencies]
hex = "0.4"
tokio = { version = "1.17.0", features = ["full"] }

[features]
default = ["local_prover"]
local_prover = [
    "once_cell",
    "dusk-plonk/std",
    "rand",
    "rusk-profile",
    "transfer-circuits",
    "std",
]
no_random = []
std = []
