[package]
name = "rusk-prover"
version = "0.3.0"
edition = "2021"
autobins = false


[dependencies]
dusk-bytes = { version = "0.1" }
dusk-wallet-core = { version = "0.25.0-phoenix.0.26", default-features = false }

## feature local_prover
once_cell = { version = "1.9", optional = true }
dusk-plonk = { version = "0.19", optional = true }
phoenix-core = { version = "0.26", features = ["alloc"], optional = true }
jubjub-schnorr = { version = "0.2", optional = true }
rand = { version = "0.8", optional = true }
rusk-profile = { version = "0.6", path = "../rusk-profile", optional = true }
transfer-circuits = { version = "0.5", path = "../circuits/transfer", optional = true }

[dev-dependencies]
hex = "0.4"
tokio = { version = "1.17.0", features = ["full"] }

[features]
default = ["local_prover"]
local_prover = [
    "once_cell",
    "dusk-plonk",
    "phoenix-core",
    "jubjub-schnorr",
    "rand",
    "rusk-profile",
    "transfer-circuits",
]
no_random = []
