[package]
name = "rusk-prover"
version = "0.3.0"
edition = "2021"
autobins = false

[dependencies]
dusk-bytes = "0.1"
once_cell = { version = "1.9" }
rand = { version = "0.8", default-features = false, features = ["getrandom"] }
dusk-plonk = { version = "0.20", default-features = false, features = ["rkyv-impl", "alloc"] }
rusk-profile = { version = "0.6", path = "../rusk-profile" }
execution-core = { version = "0.1.0", path = "../execution-core", features = ["zk"] }

[dev-dependencies]
hex = "0.4"
rand = "0.8"

[features]
no_random = []
std = [
    "dusk-plonk/std"
]
