on: [pull_request]

name: Continuous integration

jobs:
  analyze:
    name: Dusk Analyzer
    runs-on: core
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/dusk-network/cargo-dusk-analyzer
      - uses: actions-rs/cargo@v1
        with:
          command: dusk-analyzer

  test_nightly:
    name: Nightly tests
    runs-on: core
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - run: rustup component add rustfmt
      - run: rustup target add wasm32-unknown-unknown

      - name: Cache Cargo home
        uses: actions/cache@v2
        env:
          cache-name: cache-cargo-home
        with:
          # See https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: ${{env.cache-name}}-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

      - run: RUSK_PROFILE_PATH="/var/opt/build-cache" make -j test

  fmt:
    name: Rustfmt
    runs-on: core
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
