on: [pull_request]

name: Continuous integration

jobs:
  analyze:
    name: Dusk Analyzer
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo install --git https://github.com/dusk-network/cargo-dusk-analyzer
      - run: cargo dusk-analyzer

  test_nightly:
    name: Nightly tests
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: >
          RUSK_PROFILE_PATH="/var/opt/build-cache"
          RUSK_KEEP_KEYS="1"
          RUSK_BUILD_STATE="1"
          RUSK_FORCE_STATE="1"
          make test
      - name: "Clippy check release"
        env:
          RUSK_PROFILE_PATH: "/var/opt/build-cache"
        run: make clippy
      - name: "Upload Rusk Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: rusk-artifact
          path: ./target/release/rusk
          retention-days: 5
  fmt:
    name: Rustfmt
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo fmt --all -- --check
