name: Compile CLI wallet binaries

on:
  workflow_dispatch:
    inputs:
      dusk_blockchain_ref:
        description: "GIT branch to checkout"
        required: true
        default: "master"

defaults:
  run:
    shell: bash

jobs:
  build_and_publish:
    name: Build rusk-wallet binaries for ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [cargo]
        include:
          - os: ubuntu-latest
            compiler: cargo
            target: linux-x64

          - os: macos-latest
            compiler: cargo
            target: macos-intel

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.dusk_blockchain_ref }}

      - name: Install dependencies
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Add rustfmt component
        run: rustup component add rustfmt

      - name: Build Rusk binary
        shell: bash
        working-directory: ./rusk
        run: ${{matrix.compiler}} b --release --verbose -p rusk-wallet

      - name: Get semver from wallet binary
        run: |
          export SEMVER=$(./target/release/rusk-wallet --version | perl -lpe 's/\w+\s\w+\s\w+\s(.*?)/$1/')
          echo "SEMVER=$SEMVER" >> $GITHUB_ENV

      - name: "Pack binaries"
        run: |
          mkdir rusk-wallet${{env.SEMVER}}-${{matrix.target}}
          echo "Fetching changelog and readme files..."
          curl -s https://raw.githubusercontent.com/dusk-network/rusk/${{github.event.inputs.dusk_blockchain_ref}}/rusk-wallet/CHANGELOG.md > rusk-wallet${{env.SEMVER}}-${{matrix.target}}/CHANGELOG.md
          curl -s https://raw.githubusercontent.com/dusk-network/rusk/${{github.event.inputs.dusk_blockchain_ref}}/rusk-wallet/README.md > rusk-wallet${{env.SEMVER}}-${{matrix.target}}/README.md
          mv target/release/rusk-wallet rusk-wallet${{env.SEMVER}}-${{matrix.target}}
          tar -czvf ruskwallet${{env.SEMVER}}-${{matrix.target}}.tar.gz rusk-wallet${{env.SEMVER}}-${{matrix.target}}
          ls -la *.gz

      - name: "Upload Wallet Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: wallet-binaries-${{env.SEMVER}}
          path: |
            ./*.gz
          retention-days: 5
